# Generated by Django 3.2 on 2025-01-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('specialization_subject', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('experience_years_gis', models.PositiveIntegerField()),
                ('deatils_experience', models.TextField()),
            ],
        ),
    ]
