# Generated by Django 3.2 on 2025-01-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertrainer',
            name='city',
            field=models.CharField(default='Jammu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='district',
            field=models.CharField(default='Jammu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='state',
            field=models.CharField(default='Jammu and Kashmir', max_length=100),
            preserve_default=False,
        ),
    ]
