# Generated by Django 3.2 on 2025-01-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0002_auto_20250109_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertrainer',
            name='id',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
