# Generated by Django 5.1.6 on 2025-03-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0006_mastertrainer_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastertrainer',
            name='courses',
        ),
    ]
