# Generated by Django 5.1.6 on 2025-04-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0007_remove_mastertrainer_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTrainerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_id', models.CharField(max_length=20, unique=True, verbose_name='Master Trainer ID')),
                ('overall_effectiveness', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Overall Effectiveness (1-5)')),
                ('expectations_met', models.TextField(verbose_name='Did the training meet your expectations? Why or why not?')),
                ('most_useful_part', models.TextField(verbose_name='What was the most useful part of the training?')),
                ('confidence_georeferencing', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Confidence in Georeferencing (1-5)')),
                ('gcp_understanding', models.BooleanField(verbose_name='Did the session on GCPs help you understand field validation?')),
                ('clarity_of_concepts', models.BooleanField(verbose_name='Were map projections and coordinate systems explained clearly?')),
                ('implementation_challenges', models.TextField(verbose_name='Challenges in implementing georeferencing and ground truthing')),
                ('hands_on_effectiveness', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Effectiveness of Hands-on Exercises (1-5)')),
                ('materials_support', models.BooleanField(verbose_name='Did training materials support your learning effectively?')),
                ('additional_resources', models.TextField(verbose_name='Additional resources/topics that would have helped')),
                ('prepared_to_train', models.BooleanField(verbose_name='Do you feel prepared to train others?')),
                ('follow_up_support', models.TextField(verbose_name='What kind of follow-up support would be helpful?')),
                ('application_plan', models.TextField(verbose_name='How do you plan to apply georeferencing in projects?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
