# Generated by Django 5.1.6 on 2025-04-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0008_mastertrainerfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastertrainerfeedback',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='mastertrainerfeedback',
            name='additional_resources',
        ),
        migrations.RemoveField(
            model_name='mastertrainerfeedback',
            name='application_plan',
        ),
        migrations.RemoveField(
            model_name='mastertrainerfeedback',
            name='clarity_of_concepts',
        ),
        migrations.RemoveField(
            model_name='mastertrainerfeedback',
            name='confidence_georeferencing',
        ),
        migrations.RemoveField(
            model_name='mastertrainerfeedback',
            name='expectations_met',
        ),
        migrations.RemoveField(
            model_name='mastertrainerfeedback',
            name='gcp_understanding',
        ),
        migrations.RemoveField(
            model_name='mastertrainerfeedback',
            name='hands_on_effectiveness',
        ),
        migrations.RemoveField(
            model_name='mastertrainerfeedback',
            name='implementation_challenges',
        ),
        migrations.RemoveField(
            model_name='mastertrainerfeedback',
            name='overall_effectiveness',
        ),
        migrations.AddField(
            model_name='mastertrainerfeedback',
            name='download_shapefile',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainerfeedback',
            name='georeference_image',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainerfeedback',
            name='gis_concepts',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainerfeedback',
            name='import_xls',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainerfeedback',
            name='map_projections',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainerfeedback',
            name='merge_shapefiles',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainerfeedback',
            name='qfield_installation',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainerfeedback',
            name='qgis_installation',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainerfeedback',
            name='read_census_codes',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainerfeedback',
            name='set_crs',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainerfeedback',
            name='trace_polygons',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainerfeedback',
            name='transfer_qfield_project',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertrainerfeedback',
            name='upload_shapefile',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mastertrainerfeedback',
            name='follow_up_support',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastertrainerfeedback',
            name='materials_support',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mastertrainerfeedback',
            name='most_useful_part',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastertrainerfeedback',
            name='prepared_to_train',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mastertrainerfeedback',
            name='trainer_id',
            field=models.CharField(max_length=100),
        ),
    ]
