# Generated by Django 5.1.6 on 2025-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0010_mtrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtrecord',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
