# Generated by Django 5.1.6 on 2025-04-25 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0011_alter_mtrecord_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_id', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('selected_option', models.TextField()),
                ('correct_answer', models.TextField()),
                ('date_of_submission', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
